# Site settings
title: Theo Ballew
email: theoballew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whatever you want.
baseurl: "/theoballew" # the subpath of your site, e.g. /blog/
url: "http://theoballew.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  void--

# Build settings
markdown: kramdown
